# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
