# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0003_auto_20180114_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='year',
            field=models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, verbose_name='year'),
        ),
    ]
