# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0004_auto_20180114_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='vender_name',
            new_name='vendor_name',
        ),
    ]
