# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0005_auto_20180114_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
    ]
