# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Internal', '0004_auto_20180119_1658'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Devices', '0006_auto_20180114_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assign_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='possess_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possessed_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='possess_place',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possessed_devices', to='Internal.Places'),
        ),
        migrations.AlterField(
            model_name='device',
            name='whose_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='named_device', to=settings.AUTH_USER_MODEL),
        ),
    ]
