# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0008_auto_20180119_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='assigned',
        ),
        migrations.AddField(
            model_name='deviceassingment',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='Devices.Device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviceassingment',
            name='assign_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
