# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0010_auto_20180119_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetype',
            old_name='type',
            new_name='name',
        ),
    ]
