# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0011_auto_20180127_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deviceassingment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
