# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TintashPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='EmployeeProfile',
        ),
    ]
