# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internal', '0002_auto_20180119_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='TintashProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
            ],
        ),
    ]
