# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internal', '0003_tintashprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='TintashPlaces',
            new_name='Places',
        ),
        migrations.RenameModel(
            old_name='TintashProjects',
            new_name='Projects',
        ),
    ]
