# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Internal', '0004_auto_20180119_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Internal.Departments'),
        ),
    ]
