# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internal', '0005_employeeprofile_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project',
            new_name='name',
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
