# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Internal', '0006_auto_20180407_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
