# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internal', '0008_projecthours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthours',
            name='employee',
        ),
        migrations.DeleteModel(
            name='ProjectHours',
        ),
    ]
