# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internal', '0010_projecthours'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='approved_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='approved_pm',
            field=models.BooleanField(default=False),
        ),
    ]
