# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internal', '0012_auto_20180408_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthours',
            options={'verbose_name_plural': 'ProjectHours'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecthours',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
